# Generated by Django 4.2.6 on 2023-11-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
